const aulas = [
  {
    numero: "01",
    nome: "Olá Mundo!",
    data: "2026-02-23",
    caminho: "./aula01/",
    imagem: "./imgs/banner01.png",
    github: "https://github.com/diegooilv/IFRS2026/blob/main/progweb-ii/src/aula01",
  },
  {
    numero: "02",
    nome: "Exercícios",
    data: "2026-03-02",
    caminho: "./aula02/",
    imagem: "./imgs/banner01.png",
    github: "https://github.com/diegooilv/IFRS2026/blob/main/progweb-ii/src/aula02",
  },
  {
    numero: "03",
    nome: "Exercícios",
    data: "2026-03-16",
    caminho: "./aula03/",
    imagem: "./imgs/banner01.png",
    github: "https://github.com/diegooilv/IFRS2026/blob/main/progweb-ii/src/aula03",
  },
  {
    numero: "04",
    nome: "Exercícios",
    data: "2026-03-23",
    caminho: "./aula04/",
    imagem: "./imgs/banner01.png",
    github: "https://github.com/diegooilv/IFRS2026/blob/main/progweb-ii/src/aula04",
  },
  {
    numero: "05",
    nome: "Exercícios",
    data: "2026-03-30",
    caminho: "./aula05/",
    imagem: "./imgs/banner01.png",
    github: "https://github.com/diegooilv/IFRS2026/blob/main/progweb-ii/src/aula05",
  },
  {
    numero: "06",
    nome: "Exercícios",
    data: "2026-04-06",
    caminho: "./aula06/",
    imagem: "./imgs/banner01.png",
    github: "https://github.com/diegooilv/IFRS2026/blob/main/progweb-ii/src/aula06",
  },
  {
    numero: "07",
    nome: "Desafio",
    data: "2026-04-13",
    caminho: "./aula07/",
    imagem: "./imgs/banner01.png",
    github: "https://github.com/diegooilv/IFRS2026/blob/main/progweb-ii/src/aula07",
  },
  {
    numero: "08",
    nome: "Exercícios",
    data: "2026-04-27",
    caminho: "./aula08/",
    imagem: "./imgs/banner01.png",
    github: "https://github.com/diegooilv/IFRS2026/blob/main/progweb-ii/src/aula08",
  },
  {
    numero: "09",
    nome: "Exercícios",
    data: "2026-05-04",
    caminho: "./aula09/",
    imagem: "./imgs/banner01.png",
    github: "https://github.com/diegooilv/IFRS2026/blob/main/progweb-ii/src/aula09",
  },
];